### ISSUE TITLE
Problem with dgshptogrid

### ISSUE THREAD

**Issue by urskalbitzer** [r-barnes/dggridR#10]
Hi,
First of all: Thanks for implementing this package in R. It was exactly what I was searching for and the package looks great.
Unfortunately, I have a problem with with dgshptogrid function.

I was able to construct this small example, which should illustrate my problem. 

```{r}
library(dggridR)

temp.polygon <- Polygon(rbind(c(30.658062, -30.454239), c(18.423378, -34.326279), c(9.700586,   4.082381), c(-8.244678,   4.574364), c(-16.291415,  16.988192), c(33.059410,  19.501835), c(46.730717,  10.781729), c(30.658062, -30.454239)))

temp.polygons <- Polygons(list(temp.polygon),1)
temp.spatialpolygons <- SpatialPolygons(list(temp.polygons))

sp_df <- SpatialPolygonsDataFrame(temp.spatialpolygons, data.frame(ID = 1))
```

In order to use this polygone, I save it as shapefile in my working directory
```{r}
writeOGR(sp_df, "./", "sp_df_shp", driver = "ESRI Shapefile")
```

Then, I try to use dgshptogrid as shown in the example in  ?dgshptogrid
```{r}
dggs      <- dgconstruct(spacing = 25, metric = FALSE, resround = 'nearest')
new_grid <- dgshptogrid(dggs, "./sp_df_shp.shp")
```

>ERROR: polygon intersects quad #2 but a vertex of that polygon is more than 90' from the quad center.
polygon is: 
WGS84_AUTHALIC_SPHERE {
WGS84_AUTHALIC_SPHERE{(30.6581, -30.4542)}
WGS84_AUTHALIC_SPHERE{(46.7307, 10.7817)}
WGS84_AUTHALIC_SPHERE{(33.0594, 19.5018)}
WGS84_AUTHALIC_SPHERE{(-16.2914, 16.9882)}
WGS84_AUTHALIC_SPHERE{(-8.24468, 4.57436)}
WGS84_AUTHALIC_SPHERE{(9.70059, 4.08238)}
WGS84_AUTHALIC_SPHERE{(18.4234, -34.3263)}
WGS84_AUTHALIC_SPHERE{(30.6581, -30.4542)}
}

>FATAL ERROR: break-up polygon or reorient grid
running command '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/dggridR/bin/dggrid /var/folders/gy/4bhc8q_s2nbf72h98zxybz2h0000gn/T//Rtmp8SlW0X/dggridR-8a077e36d8b.meta' had status 1

I'm fairly new to geometry and mapping, and the answer might be obvious for other people, therefore I would highly appreciate any help what I have to change.

Another small problem concerns the example for the dgshptogrid-function. The path stored in 
```{r}
dg_shpfname_south_africa
```
is
>[1] "/Volumes/XT3/Builds/R-dev-web/QA/Simon/packages/el-capitan-x86_64/Rlib/3.4/dggridR/extdata/ZAF_adm0.shp"

At least in RStudio running on a Mac with macOS Sierra, this path doesn't work. However, the example worked after I downloaded the shapefile from Github and saved it locally in my working directory.

Thanks a lot,
Urs

**Comment by r-barnes** [comment]
Thanks for posting this problem, Urs.

The advice given by the package is:

    FATAL ERROR: break-up polygon or reorient grid

Unfortunately, casual searching does not show a good way to break up your polygon. If you can find a package that does something like the shortest splitline algorithm ([link](http://rangevoting.org/SplitLR.html)), that would be ideal.

Alternatively, it looks as though your polygon is a crude outline of Africa. If so, finding a shapefile of the borders of the countries of Africa would probably solve the problem.

I'm not sure why your path is wrong, but that may be fixed in the new version of the package. I'd appreciate it if you could start that as a separate issue if it's still a problem for you.

**Comment by urskalbitzer** [comment]
Thanks for your response!
Interesting link to the splitline algorithm.
The polygon is indeed a crude outline of Africe (if I remember correctly) that I constructed to post a reproducible example. It sounds as if my problem is that the the polygon is too large. I could get polygons of all countries, but my aim was to create a global grid. If I create separate grids for each country, I don't know how much the grid cells would fit to the grid cells in neighboring countries. Also for simplicity, I would prefer to create one grid per continent (or even one for the entire earth but only within continents).
However, in the mean time, I found an alternative solution using functions from the sp-package (illustrated here: http://strimas.com/spatial/hexagonal-grids/), which I will use for the moment.
But I will test your updated package with my polygon and start it as an separate issue if it's still a problem.
Thanks again,
Urs

**Comment by r-barnes** [comment]
Urs,
Cell numberings between countries should be consistent, so you can "simply" pass each country outline to dggridR and then concatenate the outputs, eliminating duplicates. The result will be the grid you need. My apologies that this is convoluted: I am working on solutions, but they will take a little while.

The problem with using the sp-package is that on an area the size of Africa you may end up with significant area distortion, which will skew your statistics.

Best regards,
Richard

**Comment by urskalbitzer** [comment]
Hi Richard,
Good to know that the cell numbering between countries should be consistent. I will also check dgearthgrid, I hadn't seen the function before, but it looks as if it's exactly what I was searching for.

My naive approach to avoid area distortion was to transform my continent/world map into an equal area projection (mollweide). Although I'm not sure if that circumvent all distortion problem (as I said, I'm totally new to spatial analyses and geography, it's just a hobby right now).

I'm following your package, so as soon as I see that you upload a new version, I will try it out.

Best,
Urs

**Comment by r-barnes** [comment]
@urskalbitzer, as of 7746fb0002225911d10896f6e511afd8e254db51 (the v2.0.0 release), I am using a new method to generate grids from shapefiles. Please give it a try and let me know if you have difficulties (be sure to adjust the `cellsize` argument of `dgshptogrid` if you have speed issues).
