### ISSUE TITLE
Problem with dgcellstogrid: lack of understanting with rgdal::OGR???

### ISSUE THREAD

**Issue by ekleins** [r-barnes/dggridR#11]
Hi, 

I've been using dggridR several months ago without any problem. Now after upgrading some libraries n my system (including the gdal libs) I'm consistently obtaining this error (using your earthquakes example, but with my own data as well):

`grid          <- dgcellstogrid(dggs, dgquakes$cell, frame=TRUE)`
_Error in ogrInfo(dsn = dsn, layer = layer, encoding = encoding, use_iconv = use_iconv,  : 
  Cannot open layer_

I've checked and `dgconstruct` is generating the KML file in my /tmp directory. I've reinstalled rgdal and dggridR. No solution with that so far.

Any ideas of what could be happening?

I'm running dggridR 1.0.1 and rgdal 1.2-8 on a Kubuntu 16.04 with R 3.4.1

Thanks, EKS

Late edit:
**NOTE:**
Playing around I've removed the _layer_ param form the `readOGR` function in `dg_process_kml` and it works. Is that the source of the problem???

**Comment by r-barnes** [comment]
Running the command

    assign("dg_debug", TRUE, envir=dggridR:::dg_env)

will provide additional debugging info that may be useful to you.

Could you post the top few sections of your KML file? Mine looks like:

    <?xml version="1.0" encoding="UTF-8"?>
    <kml xmlns="http://earth.google.com/kml/2.1">
    <Folder>
       <name>dgout</name>
       <description>Generated by DGGRID 6.2b1</description>
       <Style id="lineStyle1">
          <LineStyle id="lineStyle2">
             <color>ffffffff</color>
             <width>4</width>
          </LineStyle>
       </Style>
    <Placemark>
    <name>1</name>
          <styleUrl>#lineStyle1</styleUrl>
          <LineString>

You'll see the `<name>dgout</name>` line, which is what rgdal is looking for.

**Comment by ekleins** [comment]
This is what I have in the KML: 

```
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://earth.google.com/kml/2.1">
<Folder>
   <name>dgout</name>
   <description>Generated by DGGRID 6.2b1</description>
   <Style id="lineStyle1">
      <LineStyle id="lineStyle2">
         <color>ffffffff</color>
         <width>4</width>
      </LineStyle>
   </Style>
<Placemark>
<name>80435</name>
      <styleUrl>#lineStyle1</styleUrl>
      <LineString>
         <tessellate>1</tessellate>
         <coordinates>
```

It seems to be OK. 

Set `assign("dg_debug", TRUE, envir=dggridR:::dg_env)` and the error is he same but with more info:

after successfully generate the grid, I got

```
** grid generation complete **
accepted 1,020 cells / 1,020 tested

[1] "Metafile: /tmp/RtmpMioJPY/dggridR-2b0b40b1d68c.meta"
[1] "Inputfile: /tmp/RtmpMioJPY/dggridR-2b0b29dd3573.indat"
[1] "Cellfile: /tmp/RtmpMioJPY/dggridR-2b0b618446ff.cell_dat.kml"
Error in ogrInfo(dsn = dsn, layer = layer, encoding = encoding, use_iconv = use_iconv,  : 
  Cannot open layer

```
and all files exist in /temp...

**Comment by r-barnes** [comment]
Thank you for reporting this. As of 7746fb0002225911d10896f6e511afd8e254db51 (the v2.0.0 release), I've completely restructured the package to avoid intermediate files, thereby making it more robust against the kinds of behaviour you report. This should resolve the issue you report.
