### ISSUE TITLE
Error running dggrid.exe

### ISSUE THREAD

**Issue by msanders1** [r-barnes/dggridR#12]
Hi,

I'm trying to run dgshptogrid on a Windows machine with R3.4.1.
I've downloaded a Shapefile from Belgium and checked it using ogrinfo from gdalutils package.

> ogrinfo(dg_shpfname_belgium)
[1] "INFO: Open of `D:/projects/be_1km.shp'"
[2] "      using driver `ESRI Shapefile' successful."                
[3] "1: be_1km (Polygon)"  

However, when I try to generate a grid within the Shapefile using:
dggs      <- dgconstruct(spacing=25, metric=TRUE, resround='nearest')
sa_grid   <- dgshptogrid(dggs,dg_shpfname_belgium,frame=TRUE)

I get the error:
Error in ogrInfo(dsn = dsn, layer = layer, encoding = encoding, use_iconv = use_iconv,  : 
  Cannot open data source
In addition: Warning message:
running command 'C:/Users/msanders1/Documents/R/win-library/3.4/dggridR/bin/dggrid.exe C:\Users\MSANDE~1\AppData\Local\Temp\Rtmpw9AUrF\dggridR-1f44dd44cda.meta' had status 1

The tempfolder exists, but the meta file does not exist. A kml-file is generated.
Could someone explain what I'm doing wrong and how to solve this issue?
Thanks in advance!

**Comment by ekleins** [comment]
this problem is probably related to my post:

https://github.com/r-barnes/dggridR/issues/11

**Comment by r-barnes** [comment]
@ekleins: As of 7746fb0002225911d10896f6e511afd8e254db51 (the v2.0.0 release), I've restructured the package to avoid needing to use `dggrid.exe`. This should resolve this issue.
