### ISSUE TITLE
Documentation shows deprecated methods.

### ISSUE THREAD

**Issue by schnee** [r-barnes/dggridR#13]
`#Get the corresponding grid cells for each earthquake epicenter (lat-long pair)
dgquakes$cell <- dgtransform(dggs,dgquakes$lat,dgquakes$lon)`

from the readme. "dgtransform" is deprecated.

**Comment by r-barnes** [comment]
Thanks for letting me know.

For now, I've updated the `dgtransform` message to include a warning that notes the swapped order of arguments. I'll rebuild the examples later.
