### ISSUE TITLE
R versions supported

### ISSUE THREAD

**Issue by y-luis** [r-barnes/dggridR#14]
Documentation does not mention R versions supported, and it did not worked with Ubuntu 17.04 R package (version: 3.3.2). I ended up upgrading R version to 3.4.1 from a CRAN mirror.

**Comment by r-barnes** [comment]
For any R package this information is specified in the [DESCRIPTION](https://github.com/r-barnes/dggridR/blob/master/DESCRIPTION) file. For this project, that file states:

    Depends: R (>= 3.4.0), rgdal (>= 1.1), ggplot2 (>= 2.1), dplyr (>= 0.4), sp (>= 1.2)

While the package may work for lesser versions of these dependencies, that's not guaranteed.
