### ISSUE TITLE
Odd little issue moving from dgtransform -> dgGEO_to_SEQNUM

### ISSUE THREAD

**Issue by benlavalley** [r-barnes/dggridR#16]
Wrapping up my first project using R and running into a minor issue I was a little puzzled by.

In my code, I have this:
`circleFinal$cells <- dgtransform(dggs,circleFinal$lat,circleFinal$long)
`

Of course, I get this warning:
`Warning messages:
1: In dgtransform(dggs, circleFinal$lat, circleFinal$long) :
  The 'dgtransform(dggs,lat,lon)' function has been deprecated. Please use ' 
    dgGEO_to_SEQNUM(dggs,lon,lat)' instead! NOTE THE ARGUMENT ORDER!
`

So I change it to this:
`     circleFinal$cells <- dgGEO_to_SEQNUM(dggs, circleFinal$long, circleFinal$lat)
`

And now I get this error when that line is processed:
`Error in max(cells) : invalid 'type' (list) of argument
`

I must be missing something dead simple, right? dggridR version is 2.0.2 from this repository.

Figured I'd share a little about what I did after starting from scratch yesterday at 6pm... 

Discovered and started using R + dggridR yesterday evening after I had the need to overhaul a grid system I previously put together with turfJS and my rectangular grid system was proving wildly inconsistent in generating grids for cities around the world. After an all nighter I have it fully integrated and automating grid generation for my app. 

Many thanks to Richard Barnes and Kevin Sahr for their work on dggrid! This makes up for all the math courses I never took beyond Calc II 👍

**Comment by benlavalley** [comment]
Checked the code and found that adding $seqnum immediately to the end of my dgGeo_to_SEQNUM function seems to let it work.

**Comment by r-barnes** [comment]
@benlavalley Thanks for reporting this. I admit: the syntax is a little odd. But it makes more sense in the context of the rest of the library.

For instance, `dgGEO_to_Q2DD` returns 

```
  list(
    quad = out_quad,
    qx = out_qx,
    qy = out_qy
  )
```

each of which would have to be access similarly to `$seqnum`.

Do you think that those transformations returning only a single value should do so without requiring a `$` dereferencing?

**Comment by benlavalley** [comment]
Thanks for the prompt response on this! I'm a complete R noob so I'm only just getting used to it's syntax and nomenclature (lists, matrixes, data frames, spatial polygons, etc). I would be the last person to ask how this should actually work ;) 

I am using R to create a grid system to use for geographical API queries over cities, with my lat/lon query points varying in density based on the population, and decreasing in density as they  span out from a center point. Just threw in some code to remove points over water, and now I'm enhancing it further to add boundaries to each city and remove points outside of the boundaries. Lots of work but it should pay off with a drastic reduction in points/queries over the old very hacky grid system I created using NodeJs's turf library.

**Comment by r-barnes** [comment]
Well, ideally it is both consistent and intuitive. I fear these goals are at odds with each other here. I'll probably leave things as-is and close this comment.

Hex cells will work for the system you describe. Unfortunately, they're not a very performant solution. That is, a great deal of trigonometric and floating-point math lies behind each conversion through dggridR. For this reason, it's useful for doing spatial stats, but bad for accelerating queries. If you don't need the kinds of spatial preservation dggridR offers, an R*-tree (not sure if R has one) might be a better option.

A long-term goal is to accelerate dggridR by using vectorized operations on the backend, but there's a lot of technical debt that would need to be worked through for that to happen :-/

However, I suspect you won't notice the difference. This is more a concern if you're serving live queries to users or working with rather large datasets.
