### ISSUE TITLE
Error when implementing facet_wrap()

### ISSUE THREAD

**Issue by smjohnson670** [r-barnes/dggridR#17]
I have time series data for locations of events in a given region. I'd like to show the spatial-temporal patterns using dggridR and the facet_wrap function in ggplot. However, when I do this I get the following error:
Error in if (empty(data)) { : missing value where TRUE/FALSE needed

As an example, I extracted the month information from the dgquakes dataset using library(lubridate), and followed the example plot for dggridR. I added facet_wrap(~month) and received the same error:

    p+coord_map("ortho", orientation = c(-38.49831, -179.9223, 0))+
    +   xlab('')+ylab('')+
    +   theme(axis.ticks.x=element_blank())+
    +   theme(axis.ticks.y=element_blank())+
    +   theme(axis.text.x=element_blank())+
    +   theme(axis.text.y=element_blank())+
    +   ggtitle('Your data could look like this') +
    +   facet_wrap(~month)

> Error in if (empty(data)) { : missing value where TRUE/FALSE needed

Any suggestions on how to work around this?

**Comment by r-barnes** [comment]
@smjohnson670: Please provide a minimum working example which demonstrates the problem. I should be able to copy-paste it and have the copy-paste exactly reproduce what you are seeing.

**Comment by smjohnson670** [comment]
Like my first post noted, I'm trying to facet_wrap my data by month. Using the quake data in dggridR, I did the following:

```
#Include libraries
library(dggridR)
library(dplyr)
library(lubridate)

#Construct a global grid with cells approximately 1000 miles across
dggs          <- dgconstruct(spacing=1000, metric=FALSE, resround='down')

#Load included test data set
data(dgquakes)

#Get the corresponding grid cells for each earthquake epicenter (lat-long pair)
dgquakes$cell <- dgGEO_to_SEQNUM(dggs,dgquakes$lon,dgquakes$lat)$seqnum

#extract year and month from data
dgquakes$year <- year(dgquakes$time)
dgquakes$month <- month(dgquakes$time)

#Converting SEQNUM to GEO gives the center coordinates of the cells
cellcenters   <- dgSEQNUM_to_GEO(dggs,dgquakes$cell)

#Get the number of earthquakes each month, in each cell
quakecounts   <- dgquakes %>% group_by(month, cell) %>% summarise(count=n())

#Get the grid cell boundaries for cells which had quakes
grid          <- dgcellstogrid(dggs,quakecounts$cell,frame=TRUE,wrapcells=TRUE)

#Update the grid cells' properties to include the number of earthquakes
#in each cell
grid          <- merge(grid,quakecounts,by.x="cell",by.y="cell")

#Get polygons for each country of the world
countries <- map_data("world")

#Plot everything on a flat map
p<- ggplot() + 
  geom_polygon(data=countries, aes(x=long, y=lat, group=group), fill=NA, color="black")   +
  geom_polygon(data=grid,      aes(x=long, y=lat, group=group, fill=count), alpha=0.4)    +
  geom_path   (data=grid,      aes(x=long, y=lat, group=group), alpha=0.4, color="white") +
  geom_point  (aes(x=cellcenters$lon_deg, y=cellcenters$lat_deg)) +
  scale_fill_gradient(low="blue", high="red")
p

#Replot on a spherical projection
p+coord_map("ortho", orientation = c(-38.49831, -179.9223, 0))+
  xlab('')+ylab('')+
  theme(axis.ticks.x=element_blank())+
  theme(axis.ticks.y=element_blank())+
  theme(axis.text.x=element_blank())+
  theme(axis.text.y=element_blank())+
  ggtitle('Your data could look like this') +
  facet_wrap(~month)

Error in if (empty(data)) { : missing value where TRUE/FALSE needed
```
So - I'm not sure where the error is appearing and how to address that.

**Comment by r-barnes** [comment]
I'm afraid I'm not sure where the error's appearing either, but this is more likely something relating to your use of `ggplot` than an issue with this package. This kind of error seems to come up regularly, so it may be that searching for the error will lead to insights.

* https://groups.google.com/forum/#!topic/ggplot2/KI6Bl1UWtyc
* https://stackoverflow.com/questions/7355187/error-in-if-while-condition-missing-value-where-true-false-needed
* https://stackoverflow.com/questions/27018471/r-missing-value-where-true-false-needed/27018517
* https://stackoverflow.com/questions/7355187/error-in-if-while-condition-missing-value-where-true-false-needed/37995018
* https://github.com/tidyverse/ggplot2/issues/1394
