### ISSUE TITLE
issue with KML 

### ISSUE THREAD

**Issue by estef1** [r-barnes/dggridR#18]
I tried the below but it didn't work:

dggs          <- dgconstruct(projection="ISEA", aperture=3, topology="HEXAGON", res= 2, metric=TRUE, resround='nearest')
grid          <- dgearthgrid(dggs, frame = FALSE)
writeOGR(grid, "grid.kml", "grid", "KML")

Error in writeOGR(grid, "grid.kml", "grid", "KML") : 
  obj must be a SpatialPointsDataFrame, SpatialLinesDataFrame or
    SpatialPolygonsDataFrame

**Comment by r-barnes** [comment]
You must convert `grid` to the appropriate data type first, as described in the error message and as discussed [here](https://gis.stackexchange.com/questions/151924/writeogr-with-a-spatialpolygon-simplified-by-gsimplify).

Appropriate code looks like:

    dggs <- dgconstruct(projection="ISEA", aperture=3, topology="HEXAGON", res= 2, metric=TRUE, resround='nearest')
    grid <- dgearthgrid(dggs, frame = FALSE)
    writeOGR(as(grid, "SpatialPolygonsDataFrame" ), "/z/grid.kml", "grid", "KML")
