### ISSUE TITLE
Discrete grid using earthquake data

### ISSUE THREAD

**Issue by vmasias** [r-barnes/dggridR#19]
Dear Richard.

I was looking at the example of creating a discrete grid using earthquake data. I have 3 questions regarding how to obtain additional information:

1)  In the example provided, hexagons where there was an earthquake are extracted and nicely visualized.  This is done with the following code:  

#Get the number of earthquakes in each cell
quakecounts   <- dgquakes %>% group_by(cell) %>% summarise(count=n())

#Get the grid cell boundaries for cells which had quakes
grid          <- dgcellstogrid(dggs,quakecounts$cell,frame=TRUE,wrapcells=TRUE)

#Update the grid cells' properties to include the number of earthquakes
#in each cell
grid          <- merge(grid,quakecounts,by.x="cell",by.y="cell")

My consult is as follows. I'd like to know how to get the coordinates of hexagons (cells) where there was no record of earthquakes. I'd also like to visualize those hexagons (cells). Imagine that we want to show the **safest places on earth**, understood as those cells where there was no record of earthquakes.  How can I compute and visualize this information using earthquake data example.

2) My second question is about the "grid" object previously generated (the set of grid cell boundaries). According to my understanding, this object contains the coordinates of each cell (i. e. hexagon).  When observing each cell it is characterized by latitude and longitude values. I also noticed that the "order" column generates 7 values for each cell. What do these 7 values mean? My expectation was to find 6 values and not 7 values for each cell. Maybe I miss something. 

3) The last question is how best to calculate the centroid of each cell (without introducing unexpected bias or distortions). What would you recommend?

Again, thank you very much for making this important R package freely available.  

Best, Victor

**Comment by r-barnes** [comment]
Victor,

1. You could use `dginfo` to find the maximum number of cells. This gives you the maximum id of any cell at a given resolution. Create a vector listing all the possible ids, subtract those with earthquakes.

2. In most geospatial applications polygons (such as the hexes here) are represented by Linear Rings. A linear ring's final coordinate must match its initial coordinate. This gives you 7 coordinates.

3. I think I could generate the cell centroids (see Sahr's documentation in the vignette), but it would require some modification to the package.

Cheers,
Richard

**Comment by vmasias** [comment]
Thank you very much!

Best, Victor

**Comment by r-barnes** [comment]
Victor,
It looks as though you can generate centroids as follows:

    #Converting SEQNUM to GEO gives the center coordinates of the cells
    cellcenters   <- dgSEQNUM_to_GEO(dggs,dgquakes$cell)

**Comment by vmasias** [comment]
Dear Richard,

Thank you very much again.  I can now obtain the centroids of the cells where there was an earthquake. 

My question is the following. Is it possible to retrieve the centroid from the cells where there was no earthquake? I'm looking for the centroids of safest places on earth. 

Thank you very much again.

Victor

**Comment by r-barnes** [comment]
Victor,
You could:
1. Use `dginfo` to get the maximum number of cells. 
2. Generate a list of cell ids `1:max_num`.
3. Get the set difference of the set of earthquake cells and the previous set. These are the cells without earthquakes.
