### ISSUE TITLE
How to calculate grid distance between hexagons?

### ISSUE THREAD

**Issue by vmasias** [r-barnes/dggridR#20]
Dear Richard,

 I am trying to find distance between two hexagons, because  I would like to obtain a distance matrix between the hexagons (using the Earthquake database) What can be proper way to calculate this?

Best,

Víctor

**Comment by r-barnes** [comment]
Victor,
It depends on how you define distance. I can't help without a clearer definition.

Best regards,
Richard

**Comment by r-barnes** [comment]
A better place to ask this question is on Stackoverflow, since it pertains to performing an analysis, rather than a particular issue with this package.
