### ISSUE TITLE
"dgconstruc" (cell center points)

### ISSUE THREAD

**Issue by vmasias** [r-barnes/dggridR#21]
Dear Richard,

I've been going over the User Documentation for DGGRID version 6.2b. I noticed that the original software allows to obtain the cell center points.  

"The grid cells generated by a DGGRID run with the value GENERATE_GRID specified for the choice parameter dggrid_operation can be output as cell boundaries, **cell center points**, or both"

From what I understand, the Package ‘dggridR’ does not allow this information to be obtained. 

It´s true?  
 
Best,

Víctor

**Comment by r-barnes** [comment]
Víctor,
dggridR does not yet have that capability. It's unclear whether this should be a separate function from the other grid generators or, if not, how the centers should be stored in the returned data.

**Comment by r-barnes** [comment]
Victor,
I think I was mistaken. Back-converting from SEQNUM to GEO appears to give centroids. Though this may not be the most convenient way of retrieving the data, it does work.

    #Converting SEQNUM to GEO gives the center coordinates of the cells
    cellcenters   <- dgSEQNUM_to_GEO(dggs,dgquakes$cell)
