### ISSUE TITLE
memory usage by dgcellstogrid

### ISSUE THREAD

**Issue by jsocolar** [r-barnes/dggridR#23]
Edited to simplify reproducible example.  If I run the following code, the memory usage blows up (tens of GB), even though no objects are stored in the R environment. The issue appears both in Rstudio and R, both running R v. 3.4.4

     library(dggridR)
     
     hexgrid6 <- dgconstruct(res=6) # Construct geospatial hexagonal grid
     
     for(i in 1:1000){
       dgcellstogrid(hexgrid6, 1)
     }

**Comment by zacdav** [comment]
Bumping, I am having the same issue, particularly when iterating.
