### ISSUE TITLE
dgshptogrid produces invalid output below res=11

### ISSUE THREAD

**Issue by jzmiller1** [r-barnes/dggridR#24]
Hi! I've been testing dgshptogrid out for an area of interest and it seems to be producing some invalid outputs once I get below res=11.  Here's an example of what I'm doing:

> dggs      <- dgconstruct(res=15)
> hall_grid   <- dgshptogrid(dggs, 'C:/data/HallArea.shp', savegrid='C:/data/res15.shp')

Here's a screenshot of the output I'm getting:

![image](https://user-images.githubusercontent.com/7101735/42120580-a71a3260-7beb-11e8-8fd8-63a1ed505c34.png)

I'm not sure if the problem is with what I'm doing, what the R library does or if there's a problem inside of DGGRID itself.

**Comment by r-barnes** [comment]
The output looks alright to me. Can you clarify the problem?

**Comment by jzmiller1** [comment]
The yellow area is the polygon I'm generating the grid to cover.  At resolution 11, the brown hexagons, it generates a complete grid of hexagons to cover the area.  It does the same for res 10, 9, ... 1.  If I go to resolutions greater than 11 it only generates some of the hexagons in the area and not a complete grid.  The tiny hexagons  in the screenshot are res 15 and most of the grid is not present.

**Comment by r-barnes** [comment]
The documentation for the `dgshptogrid` command lists the following argument:
```
cellsize: Distance, in degrees, between the sample points used to
          generate the grid. Small values yield long generation times
          while large values may omit cells.
```
Adjusting this will solve the problem.
