### ISSUE TITLE
dgearthgrid creates artifacts in SpatialPolygonsDataFrame

### ISSUE THREAD

**Issue by willgearty** [r-barnes/dggridR#25]
When creating a normal data.frame with `dgearthgrid` for use with `ggplot`, the results are fine:

```r
library(dggridR)
dggs <- dgconstruct(res = 6)
grid <- dgearthgrid(dggs, frame = TRUE)
ggplot(grid) +
  aes(long,lat,group=group) +
  geom_polygon() +
  geom_path(color="white")
```

![image](https://user-images.githubusercontent.com/7232514/44821228-6bba6300-aba9-11e8-9253-a8a25f8f1170.png)

And if I then convert that to a `SpatialPolygonsDataFrame` and tidy it up for `ggplot`, still fine:

```r
grid_list <- split(grid[,c("long","lat")], grid$group)
ps <- sapply(grid_list, Polygon)
p1 <- lapply(seq_along(ps), function(i) Polygons(list(ps[[i]]), ID = names(grid_list)[i]))
grid_list_polys <- SpatialPolygons(p1, proj4string = CRS("+proj=longlat +datum=WGS84"))
grid_list_polys_df <- SpatialPolygonsDataFrame(grid_list_polys, data.frame(id = names(grid_list), row.names = names(grid_list)))
ggplot(tidy(grid_list_polys_df)) +
  aes(long,lat,group=group) +
  geom_polygon() +
  geom_path(color="white")
```

![image](https://user-images.githubusercontent.com/7232514/44821309-bd62ed80-aba9-11e8-9f14-c6552f169747.png)

But if I use `dgearthgrid` with `frame = FALSE`, it introduces artifacts into the SpatialPolygonsDataFrame:

```r
grid <- dgearthgrid(dggs, frame = FALSE)
grid <- as(grid, "SpatialPolygonsDataFrame")
ggplot(tidy(grid)) +
  aes(long,lat,group=group) +
  geom_polygon() +
  geom_path(color="white")
```

![image](https://user-images.githubusercontent.com/7232514/44821405-467a2480-abaa-11e8-86bb-d862f0345df2.png)

Furthermore, it's also an invalid spatial object:
```r
rgeos::gIsValid(grid)
# returns FALSE due to self-intersection
```

**Comment by raveem** [comment]
It's the old 180-degree-meridian-cells-wrapping-around-the-Earth problem?

**Comment by willgearty** [comment]
Yeah, that's probably what's going on. I see that there's an option to break up the cells using `wrapcells = FALSE`, but the documentation says that only works for `frame = TRUE`.

**Comment by r-barnes** [comment]
Closing this since dggridR is now using the `sf` package for output in the [latest version](https://cran.r-project.org/web/packages/dggridR/index.html).
