### ISSUE TITLE
Valgrind Issues

### ISSUE THREAD

**Issue by r-barnes** [r-barnes/dggridR#26]
Running R's valgrind

    R -d "valgrind --tool=memcheck --leak-check=full" --vanilla

produces a few run-time issues

    ==13831== Conditional jump or move depends on uninitialised value(s)
    ==13831==    at 0x2814A593: operator== (DgDiscRFS.h:57)
    ==13831==    by 0x2814A593: operator!= (DgDiscRFS.h:60)
    ==13831==    by 0x2814A593: operator= (DgDiscRFS.h:47)
    ==13831==    by 0x2814A593: DgResAdd (DgDiscRFS.h:28)
    ==13831==    by 0x2814A593: DgAddress (DgAddress.h:24)
    ==13831==    by 0x2814A593: DgRF<DgResAdd<DgIVec2D>, long>::makeLocation(DgResAdd<DgIVec2D> const&) const (DgRF_template.h:60)
    ==13831==    by 0x28161D19: DgDiscRFS2D (DgDiscRFS2D.h:39)
    ==13831==    by 0x28161D19: DgHexGrid2DS::DgHexGrid2DS(DgRFNetwork&, DgRF<DgDVec2D, long double> const&, int, unsigned int, bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, int, bool) (DgHexGrid2DS.cpp:25)
    ==13831==    by 0x2816739E: DgIDGG::initialize() (DgIDGG.cpp:901)
    ==13831==    by 0x28168091: DgIDGG::DgIDGG(DgGeoSphRF const&, DgGeoCoord const&, long double, unsigned int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, int, bool, int, unsigned int) (DgIDGG.cpp:749)
    ==13831==    by 0x281EC86F: dglib::GridThing::GridThing(long double, long double, long double, unsigned int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (dglib.cpp:87)
    ==13831==    by 0x281C3DA8: GridStat_nCells(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int) (Rwrapper.cpp:74)
    ==13831==    by 0x281D4792: Rcpp::CppFunction4<double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int>::operator()(SEXPREC**) (Module_generated_CppFunction.h:407)
    ==13831==    by 0x211F4940: InternalFunction_invoke(SEXPREC*) (Module.cpp:122)
    ==13831==    by 0x4F0DA13: ??? (in /usr/lib/R/lib/libR.so)
    ==13831==    by 0x4F4E857: Rf_eval (in /usr/lib/R/lib/libR.so)
    ==13831==    by 0x4F512DA: ??? (in /usr/lib/R/lib/libR.so)
    ==13831==    by 0x4F4E5FA: Rf_eval (in /usr/lib/R/lib/libR.so)
    ==13831== 
    ==13831== Conditional jump or move depends on uninitialised value(s)
    ==13831==    at 0x2817C5A6: operator== (DgDiscRFS.h:57)
    ==13831==    by 0x2817C5A6: operator!= (DgDiscRFS.h:60)
    ==13831==    by 0x2817C5A6: operator= (DgDiscRFS.h:47)
    ==13831==    by 0x2817C5A6: DgResAdd (DgDiscRFS.h:28)
    ==13831==    by 0x2817C5A6: DgAddress (DgAddress.h:24)
    ==13831==    by 0x2817C5A6: DgRF<DgResAdd<DgQ2DICoord>, long>::makeLocation(DgResAdd<DgQ2DICoord> const&) const (DgRF_template.h:60)
    ==13831==    by 0x28179677: DgIDGGS::DgIDGGS(DgRFNetwork&, DgGeoSphRF const&, DgGeoCoord const&, long double, unsigned int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, int, bool) (DgIDGGS.cpp:106)
    ==13831==    by 0x2817A8CC: DgIDGGS3H (DgIDGGS3H.h:27)
    ==13831==    by 0x2817A8CC: DgIDGGS::makeRF(DgRFNetwork&, DgGeoSphRF const&, DgGeoCoord const&, long double, unsigned int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, int, bool) (DgIDGGS.cpp:48)
    ==13831==    by 0x281EA8CD: dglib::GridThing::init(long double, long double, long double, unsigned int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (dglib.cpp:109)
    ==13831==    by 0x281EC9D5: dglib::GridThing::GridThing(long double, long double, long double, unsigned int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (dglib.cpp:96)
    ==13831==    by 0x281C3DA8: GridStat_nCells(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int) (Rwrapper.cpp:74)
    ==13831==    by 0x281D4792: Rcpp::CppFunction4<double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int>::operator()(SEXPREC**) (Module_generated_CppFunction.h:407)

along with many potential issues at exit.

These do not appear to materially affect operation and should be fixed upstream.

**Comment by am2222** [comment]
I tried to make its nodejs wrapper and seems there are these memory leaks cause it to break 
https://github.com/am2222/dggridjs

**Comment by r-barnes** [comment]
@am2222 : I think the memory leaks are all fixed now on master.
