### ISSUE TITLE
Any wrapper for python?

### ISSUE THREAD

**Issue by am2222** [r-barnes/dggridR#28]
Hi,
I noticed that the main library is in c++, so is there any possibility to work on a wrapper for python?I have experience working on python but I have not written wrappers for c++ libraries. Is it even possible to have a try?

**Comment by am2222** [comment]
@r-barnes Seems to be interesting,  I'll take a look at pyBind11 to figure out if I can start working on that

**Comment by am2222** [comment]
In case that anyone needs a wrapper for python I am working on that here, so far a few of functions are implemented.
It is developed on top of the R version of C++ classes
https://github.com/am2222/pydggrid/

**Comment by ldesousa** [comment]
> In case that anyone needs a wrapper for python I am working on that here, so far a few of functions are implemented.
> It is developed on top of the R version of C++ classes
> https://github.com/am2222/pydggrid/

This is a welcomed initiative, thank you for picking it up. 

I see that you replicated Kevin's C++ code in your repository. This means that long term dggridR and pydggrid can easily diverge. Some strategy should be devised so that both packages tap the same C++ library.

**Comment by am2222** [comment]
> > In case that anyone needs a wrapper for python I am working on that here, so far a few of functions are implemented.
> > It is developed on top of the R version of C++ classes
> > https://github.com/am2222/pydggrid/
> 
> This is a welcomed initiative, thank you for picking it up.
> 
> I see that you replicated Kevin's C++ code in your repository. This means that long term dggridR and pydggrid can easily diverge. Some strategy should be devised so that both packages tap the same C++ library.

Hi,
Thanks so much, You mean It is better that I update to last dggrid version? I think the latest version is 6.4. I probably do that soon, Currently my main issue is to pass geometry generated in C++ side (using boost library) to python. I was wondering to pass them as wkb format but I have no idea if that is a good strategy or not. If you have any ideas about the whole project I'd appreciate if you tell me so I can apply them.

**Comment by r-barnes** [comment]
I haven't looked at the Python code yet, but I made a number of changes to DGGRID to make it compile as a library, so the easiest way to integrate with Python would be to copy my version of DGGRID.

Kevin Sahr's working on an update to DGGRID which, I think, will fix a number of memory leaks and make it easier to import as a library. I have access to this code, but don't really have time to work on it. 

If the next version of DGGRID allows for easy library integration, then I don't see dggridR's divergence from the Python package as necessarily a bad thing. If it doesn't allow for easy integration, then the two will probably stay similar since it doesn't make sense to libraryize more than once.

**Comment by am2222** [comment]
@r-barnes Hi,
Thanks, Actually In current version I am using your code. but Recently I checked DGGRID 4.16 which compiles fine on windows but I have not tried to add it as a library. I think if a new version is capable to be added as a library it would be great. 
Also I had a question. Have you tried to compile DGGRID using MVC on windows? I could compile it using MinGW  but I was wondering if I can compile it using MVC to make pypi packages for windows

**Comment by am2222** [comment]
For MSVC  on windows I face this C2259 error  when trying to compile 64bit version
