### ISSUE TITLE
Cell sequences in geographic objects

### ISSUE THREAD

**Issue by ldesousa** [r-barnes/dggridR#29]
I am aware of two different kinds of cartographic objects that can be obtained from a DGG with dggridR:
1. Cell centres, obtained with something like:
```
dggs <- dgconstruct(res=3)
allSeqs <- seq(1, dgmaxcell(dggs))
cellCentres <- dgSEQNUM_to_GEO(dggs, allSeqs)
```
2. Cell polygons, that can be saved to disk with:
```
dggs <- dgconstruct(res=3)
allSeqs <- seq(1, dgmaxcell(dggs))
dgcellstogrid(dggs, allSeqs, frame=FALSE, savegrid="./cells.shp")
```

In neither case are the cell sequences kept with the object. `cellCentres` is an array of two lists (one for longitude and another for latitude), the shapefile saved to disk does not have attributes.

It is possible to merge cell sequences and the centres' coordinates into a single `data.frame` object, however, there is no way of knowing if the order is the same across these objects:
`df.cellCentres <- data.frame(allSeqs, cellCentres[[1]], cellCentres[[2]])`

Is there any formal way of obtaining the cells sequences for any of these objects? Can the `data.frame` example above be trusted?

**Comment by espinielli** [comment]
Maybe this will do

```
dgquakes %>% 
  dplyr::mutate(cell_id = dgGEO_to_SEQNUM(dggs, .$lon, .$lat)$seqnum) %>% 
  bind_cols(dgSEQNUM_to_GEO(dggs, .$cell_id) %>% as_tibble())

```

**Comment by good-kiwi** [comment]
I think in your `cellCentres `example, the `allSeqs` variable would already contain the cell sequence IDs and you can use `cbind` or @espinielli's example to simply merge the two.

For the `dgcellstogrid` example, I think the only use of being able to save directly to a shapefile is to visualize the grid. There is no ID information stored in the resulting shapefile, nor is there the ability to store any other gridded data into the shapefile. I don't think there would be much use to adding ID to the resulting shapefile unless some sort of other data could also be merged with it simultaneously. 

My workflow where I need a shapefile is typically 

- bin data into grids

- get grid polygons

- merge the binned data and polygons

- output to shape file

Code snippet below based on the `quakecounts` data from the vignette. I do think that the `frame=FALSE` option for `dgcellstogrid` should return a `SpatialPolygonsDataFrame` object. I can't think of a use case where a user would want a `SpatialPolygon` object instead.

```
#get grid cell boundaries
grid <- dgcellstogrid(dgg, quakecounts$cell, frame=FALSE)

#convert grid from SpatialPolygon to SpatialPolygonsDataFrame so that attribute data can be merged
grid.ID <- data.frame(ID=getSpPPolygonsIDSlots(grid), row.names=getSpPPolygonsIDSlots(grid))
grid <- SpatialPolygonsDataFrame(grid, grid.ID)


#append earthquake counts to each cell
grid <- merge(grid, quakecounts, by.x='ID', by.y='cell')

#output data to shapefile
writeOGR(grid, '_shapefile path_', '', 'ESRI Shapefile')` 
```
