### ISSUE TITLE
Version on CRAN doesn't support all grid types

### ISSUE THREAD

**Issue by ninadawn** [r-barnes/dggridR#3]
I loaded the package currently on CRAN from source. It works using the types with 3H (including 43H), but not the 4H, 4T, or 4D types.

**Comment by r-barnes** [comment]
Confirmed. Thank you for taking the time to report this. I'll look into it: how quickly do you need a fix?

**Comment by ninadawn** [comment]
I wasn't even planning to do this project until I saw you had put up this package. I wanted to but was feeling too lazy to do the necessary coding. So, the project can wait a bit longer until the library is available. Thanks for writing this package. I'm so glad it exists.

**Comment by r-barnes** [comment]
I'm glad the package will be useful to you! I've tracked down the bug and fixed it in v0.1.9 (cc7fd57).

I'm shooting for a monthly release schedule to avoid overloading the folks at CRAN, so expect this to go live to CRAN in early September.

In the meantime, you can install the package using:

    devtools::install_github('r-barnes/dggridR')

If that's inconvenient, let me know, and I can release to CRAN earlier.

**Comment by raveem** [comment]
I'd really love this released to CRAN earlier - I'm using DGGRID in an R project, and having everything available from R would be a huge boon - corporate servers don't necessarily allow devtools!

**Comment by r-barnes** [comment]
Okay: I'll submit it today.

**Comment by r-barnes** [comment]
Okay, I've just submitted.

I ended up fixing another bug that prevented compilation on old windows systems.

The submissions seem to be processed at times corresponding to morning in Europe, so we're about 12-15 hours from the earliest time this'll show up on CRAN. I'll keep you posted.

**Comment by r-barnes** [comment]
Okay, the update (v0.1.10) is propagating on CRAN.

You can see if it's available for your system by checking [here](https://cran.r-project.org/web/checks/check_results_dggridR.html).

**Comment by ninadawn** [comment]
Thanks, it works now.
