### ISSUE TITLE
Two pentagons cells

### ISSUE THREAD

**Issue by alkenani** [r-barnes/dggridR#30]
Hi Richard,

Would it be possible to explain why there are two non hexagonal cell will display when I run your code please! you can find one above the south pole.

Thanks

**Comment by alkenani** [comment]
Thanks for replying, I am using dggridR package using R, trying to save the Hexagon grids as shape file to be used in ArcMap, but the result grids are stretched where 180 180-, can you please let me know how to disconnect these grids?

**Comment by espinielli** [comment]
Could you please post the code you used?

**Comment by alkenani** [comment]
Hi, i am using two code to produce shape file,
###first code 
library(dggridR)
dggs_test <- dgconstruct(res=20)
res <- dg_closest_res_to_spacing(dggs_test,spacing=1000,round='down',metric=FALSE)
dggs_test <- dgsetres(dggs_test,res)
grid_issam <- dgearthgrid(dggs_50,savegrid="D:/New_R/shp/temp7.shp") #Save directly to a file

#second code 
dggs <- dgconstruct(res=3)
allSeqs <- seq(1, dgmaxcell(dggs))
dgcellstogrid(dggs, allSeqs, frame=FALSE, savegrid="D:/New_R/shp/temp6.shp")

**Comment by espinielli** [comment]
this does not work: `dggs_50` is unknown. Please provide a [reproducible example](https://reprex.tidyverse.org/) piece of code.

**Comment by alkenani** [comment]
Hi, thank you for your comment, could you please check below code, it's working and produce stretched cells shape file from one end to another 

#second code
dggs <- dgconstruct(res=3)
allSeqs <- seq(1, dgmaxcell(dggs))
dgcellstogrid(dggs, allSeqs, frame=FALSE, savegrid="D:/New_R/shp/temp6.shp")

**Comment by r-barnes** [comment]
I'm closing this as stale. Let me know if it's still an isuse.

Note that I've optimized the output for use with ggplot2 and haven't tested (and won't) with Arc.
