### ISSUE TITLE
Save Hexagon into shape file 

### ISSUE THREAD

**Issue by alkenani** [r-barnes/dggridR#35]
Using dggridR to save the Hexagon grids into shape file to be used in ArcMap, Cells which cross -180/180 degrees can present difficulties for plotting, As a result, such
cells will have components in the range [180,360) can you please let me know how to disconnect these grids?

code

```
library(dggridR)
dggs_test <- dgconstruct(res=20)
res <- dg_closest_res_to_spacing(dggs_test,spacing=1000,round='down',metric=TRUE)
dggs_test <- dgsetres(dggs_test,res)
grid_issam <- dgearthgrid(dggs_50,savegrid="D:/New_R/shp/temp8.shp") #Save directly to a file
gridsas <- as(dggs_50, "SpatialPolygonsDataFrame")
```

![Hexagon_DGGS_5](https://user-images.githubusercontent.com/45665596/57811765-0cb27380-7763-11e9-8651-f998492e3a48.jpg)

**Comment by good-kiwi** [comment]
Rather than saving the grid directly to a shapefile in your call to `dgearthgrid`, you can have it return a `SpatialPolygon` frame object. From there you can manipulate the polygons that are causing you trouble and then save it to a shape file with a call to `writeOGR` from the `rgdal` library

Also, I don't think your above code works as shared because `dggs_50` isn't initialized. Perhaps it should be `dggs_test` instead?

**Comment by alkenani** [comment]
thanks for that, how to do that? also can I fix 180, -180 hexagons problems.

**Comment by good-kiwi** [comment]
```
global <- dgearthgrid(dggs_test, frame=FALSE)
```
will make `global` a `SpatialPolygon` object. To convert this to a SpatialPolygonsDataFrame, you have to create an ID for each object in `global`

```
global.cell <- data.frame(cell=getSpPPolygonsIDSlots(global), row.names=getSpPPolygonsIDSlots(grid))
global <- SpatialPolygonsDataFrame(global, global.cell)
```
You can then modify all the latitudes to map to [0, 360] in a way you feel is most appropriate. Based on the map image you attached, I think your modification should be something like:
```
for(i in 1:length(global@polygons) {
  global@polygons[[i]]@polygons[[1]]@coords[,1] <- global@polygons[[i]]@polygons[[1]]@coords[,1] +360 %% 360
}
```
Then you can use a call to `saveOGR` to save this as a shapefile to load into ArcMap.You can then look at this thread here on the ESRI forum to see how to properly plot polygons that pass through the meridian: https://community.esri.com/thread/67155

**Comment by alkenani** [comment]
Thanks Joseph,
I made global a SpatialPolygon object
but for loop does not work, as line below is missing one bracket
for(i in 1:length(global@polygons) {
  global@polygons[[i]]@polygons[[1]]@coords[,1] <- global@polygons[[i]]@polygons[[1]]@coords[,1] +360 %% 360
}

**Comment by good-kiwi** [comment]
Did you do the conversion to a 'SpatialPolygonDataFrame' object? The code block proceeding the for loop does that.

**Comment by alkenani** [comment]
yes, global <- SpatialPolygonsDataFrame(global, global.cell)

**Comment by good-kiwi** [comment]
Apologies, syntax error in my code. second polygon should be capitalized
```
for(i in 1:length(global@polygons)) {
  global@polygons[[i]]@Polygons[[1]]@coords[,1] <- global@polygons[[i]]@Polygons[[1]]@coords[,1] +360 %% 360
}
```

**Comment by alkenani** [comment]
you do need to apologies, it is working ;) do I need to save global object??
writeOGR(globle, "./", "D:/New_R/shp/", driver = "ESRI Shapefile")

**Comment by good-kiwi** [comment]
```
writeOGR(global, "D:/New_R/shp/global.shp", "", "ESRI Shapefile")
```

**Comment by alkenani** [comment]
![Global](https://user-images.githubusercontent.com/45665596/60609060-b81d9300-9db8-11e9-8e69-7753f6cc3207.JPG)

**Comment by good-kiwi** [comment]
Looks like I made an error in my transformation code. Please try the following instead:
```
for(i in 1:length(global@polygons)) {
  global@polygons[[i]]@Polygons[[1]]@coords[,1] <- (global@polygons[[i]]@Polygons[[1]]@coords[,1] +360) %% 360
}
```

**Comment by alkenani** [comment]
![Global2](https://user-images.githubusercontent.com/45665596/60610077-f6b44d00-9dba-11e9-990b-264cf6b40a79.JPG)


it better, but not what I want

**Comment by alkenani** [comment]
![Global3](https://user-images.githubusercontent.com/45665596/60610283-632f4c00-9dbb-11e9-9dcf-56265ba8ebfa.JPG)
I think because cell number not fit with FID number

**Comment by good-kiwi** [comment]
It looks like my point transformation caused your issue to be shifted from the +/- 180 meridian to the 0 meridian. The FID/cell mismatch is just a mismatch between ArcMap's automatically generated IDs and the cell IDs from DGGS. It shouldn't affect the actual polygon coordinates.

I think the below will fix it by only updating the shapes that span the meridian.
```
for(i in 1:length(global@polygons)) {
  if(max(global@polygons[[i]]@Polygons[[1]]@coords[,1]) - 
     min(global@polygons[[i]]@Polygons[[1]]@coords[,1]) > 180) {
    global@polygons[[i]]@Polygons[[1]]@coords[,1] <- (global@polygons[[i]]@Polygons[[1]]@coords[,1] +360) %% 360
  }
}
```

**Comment by alkenani** [comment]
Hello Joseph, I've tried your your updated code, it is looking better thank you. however, in comparison with hexagons cells similar sizes there are few problem on some cells on the right had side covering (Alasca, Antarctica) all hexagon cells outside the map frame. 
![error](https://user-images.githubusercontent.com/45665596/60867234-431be480-a222-11e9-9cce-ba37d2146a19.JPG)

**Comment by alkenani** [comment]
![correct_cells](https://user-images.githubusercontent.com/45665596/60867351-8b3b0700-a222-11e9-8a9e-6ab54c87698a.JPG)
it should look like this hexagon cells

**Comment by alkenani** [comment]
![error2](https://user-images.githubusercontent.com/45665596/60869258-87a97f00-a226-11e9-8395-f67186917a8c.JPG)
if we combined two layers (blue the correct and red is your code, you can notice the cells on the right hand side and one missing on the top

**Comment by good-kiwi** [comment]
The red cells on the right are the ones that are supposed to wrap around and include the missing areas on the left hand side of your map. I think there is some functionality in ArcMap to take those red cells and split them into 2 shapes clipped by the +180/-180 Meridian and move the corresponding piece to the other side of the map. The link I posted in my first response should give some hints on how to do that. I'm not sure how to do it myself.

As for the cell on the top, I am not sure why it is not displayed. Have you checked that the global variable contains that cell? The last code I posted might be incorrectly modifying it. You can try increasing the 180 threshold to something like 270?

**Comment by alkenani** [comment]
Using 270 has solved top cell, thanks for help. 

i am doing research on the following:-
Have you managed to work with raster vector layers ? 
Have you used two or three cell sizes in the same time to display data, for example big size cells to represent  rural density meanwhile small cells for urban density?

thanks again

**Comment by good-kiwi** [comment]
I'm a bit confused on what you are trying to do. Density is dependent on the area of the grid you are using. So modifying the grid size for areas of lower density and areas of higher density will cause some distortion among your measures. To rectify this, you will have to normalize your statistics by the area of each cell. This sort of goes against the idea of using a uniform grid.

If you are simply trying to visualize some data, perhaps something like this would be easier to use:
http://desktop.arcgis.com/en/arcmap/10.3/map/working-with-layers/using-proportional-symbols.htm

**Comment by good-kiwi** [comment]
@alkenani, if you are satisfied that you have been able to get the answer to your original question, please mark this issue as closed.

**Comment by r-barnes** [comment]
But please open a pull request if there's a way to improve the documentation/code.

**Comment by good-kiwi** [comment]
@r-barnes, I opened another issue to discuss some possible improvements. I cribbed the 180 filter idea I posted in this thread from the `dg_process_polydata` function and through this exercise found that 180 won't really cover all the edge cases. Working my way towards improving that and will post a pull request for it. 

I think ideas from this thread can be used to improve how the `SpatialPolygons` are created to make generating shape files a bit more straightforward for this scenario.

**Comment by andrei0807** [comment]
@alkenani Can you share last full code?

**Comment by andrei0807** [comment]
![image](https://user-images.githubusercontent.com/32348752/140024461-fae1e98c-e225-43cb-bc01-1ba1dcf3a4e8.png)
When I use shape for 3D map in ArcGIS pro, top and bottom are not correct and there are long line.
How to fix this issue?

**Comment by r-barnes** [comment]
Closing this since it might be stale with dggridR's move to the `sf` package in the [latest version](https://cran.r-project.org/web/packages/dggridR/index.html).
