### ISSUE TITLE
suggestion: Give relative coordinates of lat-long within a cell

### ISSUE THREAD

**Issue by ninadawn** [r-barnes/dggridR#4]
Given a lat-long, I can get a cell address. It would be cool to get it's relative location in the cell after the projection. For example, let's assume the shape exists in an x-y plane and the centroid of a shape is the origin. We could also always assume that a shape is a constant size, regardless of the actual scale, say inscribed in the unit circle. Then I might have a point go from a given lat long to cell 1432 with relative coordinate (-0.24, 0.4). 

This doesn't appear to be functionality in the underlying dggrid, but when you move to another library, it would be very helpful to have if available.

**Comment by r-barnes** [comment]
@ninadawn: This functionality should now be available as of 7746fb0002225911d10896f6e511afd8e254db51 with either `dgGEO_to_PROJTRI()` or `dgGEO_to_Q2DD()` or `dgGEO_to_Q2DI()`.

I have not experimented extensively with this, so let me know if you have issues or an interesting vignette you'd like to contribute.

Sorry about the delay!
