### ISSUE TITLE
Add a cell column to spatial output of dgcellstogrid() and dgearthgrid()

### ISSUE THREAD

**Issue by mstrimas** [r-barnes/dggridR#40]
When called with `frame = TRUE`, both `dgcellstogrid()` and `dgearthgrid()` return a data frame with a cell column that's useful for joining to other data. However, when `frame = FALSE` is used a `SpatialPolygons` object is returned that doesn't provide a way to connect which cell number corresponds to each polygons. These functions would be much more useful if they returned `SpatialPolygonsDataFrame` objects with the cell number.

**Comment by mstrimas** [comment]
I'd be happy to submit a PR for this if it's something you'd be open to

**Comment by SebKrantz** [comment]
This issue has been fixed and should be closed.
