### ISSUE TITLE
Allow user to create dgg using arbitrary sequence of apertures of type 3,4, and 7

### ISSUE THREAD

**Issue by senorhesles** [r-barnes/dggridR#41]

**Comment by senorhesles** [comment]
We spoke about this offline. I figured I'd get an issue opened to track it.

**Comment by r-barnes** [comment]
@senorhesles - This got stale, so I'm going to close for now. If it's still an issue for you, would you remind me whether DGGRID itself has this functionality?

**Comment by sadbasilisk** [comment]
@r-barnes it does; I ended up just using DGGRID directly.

**Comment by senorhesles** [comment]
@r-barnes DGGRID does have this functionality; I ended up just using DGGRID directly.
