### ISSUE TITLE
dggridR back on CRAN

### ISSUE THREAD

**Issue by mstrimas** [r-barnes/dggridR#42]
I just noticed dggridR has been archived, any intention of getting it back on CRAN?

**Comment by r-barnes** [comment]
I am working on getting it back on CRAN. The process is onerous. Thank you for checking in :-)

**Comment by lvalnegri** [comment]
I've just noticed dggridR has been archived again :-(

**Comment by r-barnes** [comment]
Thanks for the heads-up! I think a couple of URLs were missing slashes. I should be able to get it resubmitted later today.

**Comment by r-barnes** [comment]
Okay, it's resubmitted.

**Comment by jens-daniel-mueller** [comment]
Hi Richard,
I would like to use dggrid for the first time, but currently it seems to be archived on CRAN.
Do I see this correctly?
And if yes, do you plan to bring it back to CRAN?
And if yes, any idea when it could become available again?
Thanks for a quick update on the situation!
Jens

**Comment by r-barnes** [comment]
Jens,
I'm aware of the situation. CRAN regularly audits packages and found that dggridR has memory leaks. While these shouldn't affect results, it does mean that dggridR can't return to CRAN until they're fixed. The leaks themselves come from upstream libraries; I'm working with the authors to fix those. In the meantime, you could try:
```
devtools:::install_github("r-barnes/dggridR")
```

**Comment by jens-daniel-mueller** [comment]
Dear Richard,
thanks for updating us on the situation. I keep my fingers crossed that you guys manage to solve the leak issues in the upstream libraries, and will rely on the installation from github for now. Dropping a short note here when the package is back on CRAN would be very much appreciated.
Cheers!

**Comment by edzer** [comment]
@r-barnes it seems that the downstream memory issues have been solved: https://github.com/sahrk/DGGRID/issues/24 - have you tried updating & resubmitting this package to CRAN?

**Comment by r-barnes** [comment]
@edzer : That's true. The API has changed, though. I'm actually working today on building a new bridge between R and that API.

**Comment by r-barnes** [comment]
@edzer : I've got things apparently working with the newest version of DGGRID now. That's available on the branch "https://github.com/r-barnes/dggridR/tree/update_from_upstream". I haven't had much chance to test it yet.

Unfortunately, I am probably not able to get it on CRAN yet. There are some [Valgrind issues](https://github.com/sahrk/DGGRID/issues/37) that need to be dealt with and CRAN tends to be very (overly?) strict about these. Kevin's usually pretty good at responding, though, so I hope we can move this forward.

**Comment by willgearty** [comment]
@r-barnes It looks like all the DGGRID issues have been resolved; any chance this will be on CRAN again anytime soon?

**Comment by r-barnes** [comment]
@willgearty - Yes, the only issue left I'm aware of is something with BuildVignette not working, that and working up the energy to interact with the CRAN submission process again. I'll try to prioritize getting on this.

**Comment by edzer** [comment]
FYI: CRAN submissions will be offline from Jul 22, 2022 to Aug 5, 2022 (CRAN team vacation and maintenance work).

**Comment by rion-saeon** [comment]
@r-barnes the package is not compatible with R4.2.2

**Comment by r-barnes** [comment]
Can you provide any additional details such as error messages?

**Comment by rion-saeon** [comment]
A `remotes` install produced the following log that I quitted. Could not tell whether a recurring loop was happening preventing the install to finish.

[remotes_install_log.txt](https://github.com/r-barnes/dggridR/files/10195468/remotes_install_log.txt)

**Comment by edzer** [comment]
Don't quit it, it seems to just not have finished. How long did you wait?

**Comment by r-barnes** [comment]
Looks as though things are working based on this excerpt. There are a large
number of files that need to be compiled.

**Comment by edzer** [comment]
I ran a `R CMD check --use-valgrind`, and did not stumble upon valgrind errors, but there was another error which for some reason was not caught during check _without_ using valgrind: 
[00check.log.txt](https://github.com/r-barnes/dggridR/files/10195528/00check.log.txt)

**Comment by rion-saeon** [comment]
Take #2. Stand by...

**Comment by edzer** [comment]
Now, while checking under valgrind, reduced to
```
--- re-building ‘dggridR.Rmd’ using rmarkdown
Loading required package: dplyr

Attaching package: 'dplyr'

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

Loading required package: rlang
Loading required package: sf
Linking to GEOS 3.10.2, GDAL 3.4.3, PROJ 8.2.1; sf_use_s2() is TRUE
Loading required package: sp
Quitting from lines 16-47 (dggridR.Rmd) 
Error: processing vignette 'dggridR.Rmd' failed with diagnostics:
Problem while computing `..1 = lengths(.predicate(x, y, ...)) > 0`.
Caused by error in `wk_handle.wk_wkb()`:
! Loop 0 is not valid: Edge 3 crosses edge 6
--- failed re-building ‘dggridR.Rmd’
```

**Comment by edzer** [comment]
For some context:
* validity on the sphere: https://r-spatial.org/book/04-Spherical.html#validity-on-the-sphere and 
* why this is important: https://r-spatial.org/r/2020/06/17/s2.html

**Comment by edzer** [comment]
`R CMD check --use-valgrind` checks cleanly, with this PR.

**Comment by edzer** [comment]
Let me know if you want help modifying all `sprintf` instances into using `snprintf` - I just did a large edit of lwgeom (also a larger external library) here: https://github.com/r-spatial/lwgeom/commit/2d157e402d9a63514a5c9bdf21e6906a58c57292

**Comment by r-barnes** [comment]
@edzer - That'd be great, if you have time.

**Comment by r-barnes** [comment]
@edzer - Thanks! I'm attempting to build again now.

**Comment by edzer** [comment]
Did you succeed?

**Comment by r-barnes** [comment]
@edzer - After some more fiddling dggridR has passed all the pre-submission checks and has gone on to manual review. Thank you for your help with this.
