### ISSUE TITLE
dgearthgrid broken in R 4.0.0

### ISSUE THREAD

**Issue by willgearty** [r-barnes/dggridR#43]
The following works fine in R 3.6.3, but fails in R 4.0.0:

```r
dggs <- dgconstruct(res = 6)
grid <- dgearthgrid(dggs, frame = TRUE)
```
The error says that it can't find the function `GlobalGrid`.

**Comment by mstrimas** [comment]
FYI this works fine for me on R 4.0.0 and dggridR installed from github repo, you may need to provide a little more context so the issue can be reproduced.

**Comment by willgearty** [comment]
Whoops, looks like I hadn't updated to Rtools 4.0. Somehow the package was able to be installed from source despite not being compiled properly. Works now!
