### ISSUE TITLE
Vignette not available

### ISSUE THREAD

**Issue by Labarcena-Jessica** [r-barnes/dggridR#45]
Hello, 

After installing the package using install_github('r-barnes/dggridR',  build_vignettes = TRUE) I get this error 
Error in loadVignetteBuilder(pkgdir, TRUE) : 
     vignette builder 'R.rsp' not found
   Execution halted
Error: Failed to install 'dggridR' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr:

Following your recommendation of using install_github('r-barnes/dggridR', vignette=TRUE) the error is vignette 'dggridR' not found. 

I think there is an issue with building the vignette.

**Comment by 16TWQ** [comment]
> Hello,
> 
> After installing the package using install_github('r-barnes/dggridR', build_vignettes = TRUE) I get this error Error in loadVignetteBuilder(pkgdir, TRUE) : vignette builder 'R.rsp' not found Execution halted Error: Failed to install 'dggridR' from GitHub: System command 'R' failed, exit status: 1, stdout + stderr:
> 
> Following your recommendation of using install_github('r-barnes/dggridR', vignette=TRUE) the error is vignette 'dggridR' not found.
> 
> I think there is an issue with building the vignette.

I am facing the same issue, just wonder have you already solve out the problem?

**Comment by r-barnes** [comment]
My apologies. I'm working on getting a new version out, but CRAN has _very_ strict admission criteria for code that have been difficult to meet with a codebase not designed to handle them.

**Comment by 16TWQ** [comment]
Hello Richard,

Thank you very much for your reply. Just wonder, which is the highest version of R that you are suggest to use dggridR for now if i install it through local zip file?
Thank you very much for your effort!!

Wanqing Tai

________________________________

**Comment by r-barnes** [comment]
@16TWQ : It appears to work with 4.1.2 on my machine. I don't have a priori reasons to think it wouldn't work with higher versions.

**Comment by r-barnes** [comment]
@Labarcena-Jessica and @16TWQ - this doesn't appear to be a problem any more. Closing the issue.
