### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by twiebke** [r-barnes/dggridR#46]
It seems that is not possible to install diggridR on R 4.0
`install.packages('dggridR')
Installiere Paket nach ‘/home/R/x86_64-pc-linux-gnu-library/4.0’
(da ‘lib’ nicht spezifiziert)
Warnmeldung:
package ‘dggridR’ is not available for this version of R
`
and 
`install_github('r-barnes/dggridR', vignette=TRUE)`
or
`install_github('r-barnes/dggridR')`
gave some error:
`g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I'/usr/local/lib/R/site-library/Rcpp/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-fhxXXR/r-base-4.0.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c util.cpp -o util.o
g++ -std=gnu++11 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o dggridR.so DgAddressBase.o DgBase.o DgBoundedHexC2RF2D.o DgBoundedIDGG.o DgBoundedIDGGS.o DgBoundedRF2D.o DgBoundedRFS2D.o DgCell.o DgColor.o DgConverterBase.o DgDVec2D.o DgDVec3D.o DgDiscRFS2D.o DgDistanceBase.o DgDmdD4Grid2D.o DgDmdD4Grid2DS.o DgDmdD8Grid2D.o DgDmdD8Grid2DS.o DgEllipsoidRF.o DgGeoSphRF.o DgHexC1Grid2D.o DgHexC2Grid2D.o DgHexGrid2DS.o DgIDGG.o DgIDGGS.o DgIDGGS3H.o DgIDGGS43H.o DgIDGGS4D.o DgIDGGS4H.o DgIDGGS4T.o DgIVec2D.o DgIVec3D.o DgIcosaMap.o DgInAIGenFile.o DgInLocTextFile.o DgInShapefile.o DgInShapefileAtt.o DgInputStream.o DgLocBase.o DgLocList.o DgLocVector.o DgLocation.o DgOutAIGenFile.o DgOutGeoJSONFile.o DgOutKMLfile.o DgOutLocFile.o DgOutLocTextFile.o DgOutPtsText.o DgOutRandPtsText.o DgOutShapefile.o DgOutputStream.o DgParamList.o DgPolygon.o DgProjFuller.o DgProjGnomonicRF.o DgProjISEA.o DgProjTriRF.o DgRFBase.o DgRFNetwork.o DgRandom.o DgSeriesConverter.o DgSqrD4Grid2D.o DgSqrD4Grid2DS.o DgSqrD8Grid2D.o DgSqrD8Grid2DS.o DgSuperfund.o DgTriGrid2D.o DgTriGrid2DS.o DgUtil.o RcppExports.o Rwrapper.o adjlon.o clipper.o dbfopen.o dglib.o hypot.o pj_auth.o pj_mlfn.o pj_msfn.o pj_phi2.o pj_qsfn.o pj_tsfn.o safileio.o sbnsearch.o shpopen.o shptree.o util.o -L/usr/lib/R/lib -lR
installing to /home/R/x86_64-pc-linux-gnu-library/4.0/00LOCK-dggridR/00new/dggridR/libs
** R
** data
** inst
** byte-compile and prepare package for lazy loading
free(): invalid pointer
Aborted (core dumped)
ERROR: lazy loading failed for package ‘dggridR’
* removing ‘/home/R/x86_64-pc-linux-gnu-library/4.0/dggridR’
Fehler: Failed to install 'dggridR' from GitHub:
  (konvertiert von Warnung) installation of package ‘/tmp/RtmpGc4tc6/fileafbe56af62a6/dggridR_2.0.8.tar.gz’ had non-zero exit status`

Is there a chance to fix ist?

**Comment by r-barnes** [comment]
I hope to fix this and several issues in a couple of weeks. I'm simultaneously getting an OS upgrade and fixes from upstream.

**Comment by 16TWQ** [comment]
![image](https://user-images.githubusercontent.com/53305678/153380832-ec041e36-b643-4186-befa-03563b5198be.png)
Hello, i have a same problem on installation failling in R (4.1.1). Does anyone have another way? Should i download R3.x back? Thanks

**Comment by r-barnes** [comment]
I'm still working on this and have made another submission to CRAN.

**Comment by r-barnes** [comment]
```
devtools::install_github("r-barnes/dggridR", branch="install_github")
```
works

**Comment by 16TWQ** [comment]
Hello Richard,

Thank you very much, I reinstalled my R and R studio, then i am ok to install! Really helpful, thank you again!

Best wishes
Wanqing Tai
________________________________

**Comment by igloopigloo** [comment]
> 



> ```
> devtools::install_github("r-barnes/dggridR", branch="install_github")
> ```
> 
> works

Hi,

I tried the suggested devtools option
```devtools::install_github("r-barnes/dggridR", branch="install_github")```

But I am getting following error:
**Warning in system(cmd) : 'make' not found
ERROR: compilation failed for package 'dggridR'
* removing 'C:/Users/sh55451/AppData/Local/Programs/R/R-4.2.0/library/dggridR'**
Can you please help here? This will really help me out.

Thanks.
