### ISSUE TITLE
suggestion: Allow for setting the initial icosahedron orientation

### ISSUE THREAD

**Issue by ninadawn** [r-barnes/dggridR#5]
It would be nice to be able to adjust the orientation of the icosahedron by setting the location of one vertex and adjusting the rotation.

**Comment by r-barnes** [comment]
@ninadawn: I'm not sure when I'll get around to building out this interface, but you can edit the dggs object directly to achieve what you want. Just use:

    dggs[['PROPERTY_NAME']] = VALUE

for each thing you want to set and they will be passed to DGGRID in an appropriate manner.

**Comment by ninadawn** [comment]
Ah, cool. Thanks.

**Comment by r-barnes** [comment]
@ninadawn: I've just released dggridR v1.0.1. This should include support for setting the initial orientation of the icosahedron, per your request. You can do so by setting parameters in the call to `dgconstruct()`. See the documentation of that function for details. Do let me know if you encounter any issues!
