### ISSUE TITLE
Can dggridR output neighbors of each cell?

### ISSUE THREAD

**Issue by lilangping** [r-barnes/dggridR#53]
Dear Richard,

I am aware that DGGRID can output neighbors of cells by setting parameters "neighbor_output_***" in the Metafile

I wonder can dggridR output neighbors of each cell? How to do it?

I checked all the files of dggridR and didn't find the answer.

Thank you very much, for your fantastic algorithms!

Best regards,
Langping

**Comment by r-barnes** [comment]
Not at the moment, though [this blog](https://nadiah.org/2021/09/29/find-cell-neighbours-isea3h/) explains one method for doing it.

**Comment by lilangping** [comment]
> Not at the moment, though [this blog](https://nadiah.org/2021/09/29/find-cell-neighbours-isea3h/) explains one method for doing it.

Thank you, Richard!
