### ISSUE TITLE
vignette ‘dggridR’ not found 

### ISSUE THREAD

**Issue by hccs-2o2o** [r-barnes/dggridR#56]
Hi.
When I run the command vignette('dggridR') I get following message:
vignette ‘dggridR’ not found 

Please, could you advise what I might have done wrong?
Thank you.

**Comment by r-barnes** [comment]
I've uploaded a [new version](https://cran.r-project.org/web/packages/dggridR/index.html) of dggridR in which the vignette should be working. Please let me know if that turns out not to be the case.
