### ISSUE TITLE
Add cell centers

### ISSUE THREAD

**Issue by bart1** [r-barnes/dggridR#6]
For certain applications it would be good to be able to retrieve the centers of grid cells. For example when looking at connectivity networks. It also would be quicker to work with the high resolution data when the points could be a good approximation of the full grid. The grid cell centers are as far as i know generated  and reported in the .gen files (e.g http://webpages.sou.edu/~sahrk/dgg/isea.old/gen/isea3h.html )

**Comment by raveem** [comment]
This would be very useful. In R, the shapefile produced by DGGRID only has global_id in as easily accessible in the S4 container, e.g., GRID@data$global_id. The rest are hidden in obscure corners of the S4 container and utterly inaccessible unless dug out one by one.

Adding in cell centres would therefore be of huge utility, e.g.:

GRID@data$Lon
GRID@data$Lat

**Comment by r-barnes** [comment]
@raveem: Would the more general functionality described by Issue #4 provide what you need?

**Comment by bart1** [comment]
I'm not sure if that would work because it would not really give an easy option to retrieve all cell centers as far as I can see

**Comment by raveem** [comment]
I agree with bart1. Given how ubiquitously useful Lon and Lat are, I'd prefer just simply tacking them on as extra columns as part of the default output of DGGRID, rather than as an output from any other process.

**Comment by r-barnes** [comment]
@bart1 and @raveem: As a subscriber to the "do one thing well" philosophy, I'm hesitant to make this an obligate output of the library.

However, as of 7746fb0002225911d10896f6e511afd8e254db51 (the v2.0.0 release), it is now possible to capture the functionality you want, as I demonstrate below:

    library(dggridR)
    library(dplyr)

    #Construct a global grid with cells approximately 1000 miles across
    dggs          <- dgconstruct(spacing=1000, metric=FALSE, resround='down')

    #Load included test data set
    data(dgquakes)

    #Get the corresponding grid cells for each earthquake epicenter (lat-long pair)
    dgquakes$cell <- dgGEO_to_SEQNUM(dggs,dgquakes$lon,dgquakes$lat)$seqnum

    #Get centers of the cells (THIS LINE IS KEY!)
    cellcenters   <- dgSEQNUM_to_GEO(dggs,dgquakes$cell)

    #Get the number of earthquakes in each cell
    quakecounts   <- dgquakes %>% group_by(cell) %>% summarise(count=n())

    #Get the grid cell boundaries for cells which had quakes
    grid          <- dgcellstogrid(dggs,quakecounts$cell,frame=TRUE,wrapcells=TRUE)

    #Update the grid cells' properties to include the number of earthquakes
    #in each cell
    grid          <- merge(grid,quakecounts,by.x="cell",by.y="cell")

    #Make adjustments so the output is more visually interesting
    grid$count    <- log(grid$count)
    cutoff        <- quantile(grid$count,0.9)
    grid          <- grid %>% mutate(count=ifelse(count>cutoff,cutoff,count))

    #Get polygons for each country of the world
    countries <- map_data("world")

    #Plot everything on a flat map
    p<- ggplot() + 
        geom_polygon(data=countries, aes(x=long, y=lat, group=group), fill=NA, color="black")   +
        geom_polygon(data=grid,      aes(x=long, y=lat, group=group, fill=count), alpha=0.4)    +
        geom_path   (data=grid,      aes(x=long, y=lat, group=group), alpha=0.4, color="white") +
        geom_point  (aes(x=cellcenters$lon_deg, y=cellcenters$lat_deg)) +
        scale_fill_gradient(low="blue", high="red")
    p

I'll add this to the vignettes as well, though that won't make it in until a future release.

**Comment by r-barnes** [comment]
Actually, I've got it into the vignette in 8ac25d34772ed8ff9984f3a91e4e4693a2e8d9c6 (v2.0.1)

**Comment by bart1** [comment]
Thank you for the addition, it will come in very useful for some of my work!

**Comment by r-barnes** [comment]
No worries! I'd love to hear at some point what you're doing with it!

**Comment by bart1** [comment]
Some of the work relates to bird migration routes, using the grid as an grid to travel on (eg http://onlinelibrary.wiley.com/doi/10.1111/ele.12528/abstract )

**Comment by bart1** [comment]
http://www.bioinfo.mpg.de/flyways/ <- a bit more accessible visualization of the results

**Comment by raveem** [comment]
Using it for a fine grain grid to cover all human built up areas for terrorism insurance modelling :).

**Comment by r-barnes** [comment]
Are these changes working out for everyone?

(Also @bart1, that's really cool stuff in your paper! A lot of my work is in applying high-performance computing techniques to ecology: if you ever hit a problem that would benefit from that we should chat :-) )
