### ISSUE TITLE
package citation

### ISSUE THREAD

**Issue by edzer** [r-barnes/dggridR#7]
The vignette says: "Please cite this package as: Richard Barnes (2016). dggridR: Discrete Global Grids for R. https://github.com/r-barnes/dggridR." However, 
```r
> citation("dggridR")

To cite package ‘dggridR’ in publications use:

  Richard Barnes (2016). dggridR: Discrete Global Grids for R. R
  package version 0.1.11. https://CRAN.R-project.org/package=dggridR

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {dggridR: Discrete Global Grids for R},
    author = {Richard Barnes},
    year = {2016},
    note = {R package version 0.1.11},
    url = {https://CRAN.R-project.org/package=dggridR},
  }
```
You could add a `CITATION` file to the package, but I'd suggest to go for the canonical (default) citation, since google scholar tends to pick these up.

**Comment by r-barnes** [comment]
To clarify, are you suggesting replacing the vignette text with the result of `citation('dggridR')`?

**Comment by edzer** [comment]
Yes.

**Comment by r-barnes** [comment]
Thanks, I'll update per your suggestion that in the next release.
