### ISSUE TITLE
CRAN version fix?

### ISSUE THREAD

**Issue by alban-idiv** [r-barnes/dggridR#73]
Dear @r-barnes,

Our BioTIMEr package was kicked out of CRAN in April because our use of dggridR failed on their Mac M1 system ([error report here](https://www.r-project.org/nosvn/R.check/r-release-macos-arm64/BioTIMEr-00check.html)).

Porting @SebKrantz's fix to CRAN would help us and others to fully and reliably use dggridR and publish our work.

Hoping for a positive outcome soon and thank you for the great package

**Comment by SebKrantz** [comment]
@alban-idiv dggridR v3.1.0 has made it to CRAN. I am the new maintainer.

**Comment by AlbanSagouis** [comment]
Preparing our resubmission to CRAN just now. Thank you so much!

**Comment by AlbanSagouis** [comment]
And Thanks @r-barnes , BioTIMEr was accepted and it's back on CRAN!
