### ISSUE TITLE
Suggestion: Output grids as polygons.

### ISSUE THREAD

**Issue by robholorama** [r-barnes/dggridR#8]
Hi there

Really great package, I've been using global grids for analysis of ecological data for a few years so this is a fantastic tool. I wonder whether it would be possible to add the function to generate a polygon of the grids as an output. I've spent a few days trying to generate these from the polylines (and the underlying point data) but polylines that cross the meridian for some reason double back on themselves so you end up with a set of polygons with huge areas, effectively spanning the globe. I will keep having a fiddle with it and if I manage to code this up I will get in touch, but otherwise perhaps a function for a future release. 

All the best

Rob Holland

**Comment by r-barnes** [comment]
Rob,
Thanks for getting in touch! (And for using the Issues function on Github: it makes questions and requests easier to deal with.)

If you're trying to print polygons to a two-dimensional map, such as a Mercator projection, you should look at the `wrapcells` option, which is available in functions such as `dgcellstogrid()` and `dgearthgrid()`. These will break polygons which cross the 180th meridian into separate pieces, avoiding the problem you describe. If you need to break on a different meridian, looking at the `dg_process_kml()` function in the dggridR source should get you started.

Alternatively, you could plot your data in 3D using my new package [webglobe](https://github.com/r-barnes/webglobe). See [this page](https://github.com/r-barnes/webglobe/blob/master/vignettes/webglobe.Rmd) for an example of how to integrate it with dggridR.

I hope that helps!
